etaxi/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('etaxi.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

etaxi/etaxi/urls.py
from django.urls import path
from . import views

app_name = 'etaxi'
urlpatterns = [
    path('', views.home, name='home'),
    path('etaxi/<str:city>', views.home, name='homecity'),
    path('etaxi/<str:city>/contacts/', views.contacts, name='contacts'),
    path('etaxi/<str:city>/about/', views.about, name='about'),    
] 

etaxi/etaxi/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from embed_video.fields import EmbedVideoField
from .validators import DriverNameValidator

# Create your models here.
class City(models.Model):
    name = models.CharField(verbose_name='Город', max_length=200)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Города"
        verbose_name = 'Город'
        
class CityPark(models.Model):
    name = models.CharField(verbose_name='Город', max_length=200)
    latitude = models.FloatField(verbose_name='Широта', null=False)
    longitude = models.FloatField(verbose_name='Долгота', null=False)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Города"
        verbose_name = 'Город'
        ordering = ['name']
        
class Driver(models.Model):
    name = models.CharField(validators=[DriverNameValidator], verbose_name='Водитель', max_length=40, blank=False, null=False)
    phone_number = PhoneNumberField(verbose_name='Телефон', null=False, blank=False)
    dateCreation = models.DateTimeField(auto_now_add=True)
    city = models.ForeignKey(CityPark, on_delete=models.CASCADE, verbose_name='Город', blank=True, null=True,)
    confirmation = models.BooleanField(verbose_name='Соглашение на обработку получено', default=True)
    question = models.TextField(max_length=500, blank=True, null=True, verbose_name='Вопрос клиента' )
    
    class Meta:
        verbose_name_plural = "Водители"
        verbose_name = 'Водитель'
        
    def __str__(self):
        return f'{self.name} ({self.phone_number})'
    
class TaxiCar(models.Model):
    SEDAN = 'SD'
    HATCHBACK = 'HT'
    LIFTBACK = 'LF'
    JEEP = 'JP'
    UNIVERSAL = 'UN'
    MINIVAN= 'MW'
    PIKUP = 'PK'

    CATEGORY_CHOICES = (
        (SEDAN, 'Седан'),
        (HATCHBACK, 'Хэтчбэк'),
        (LIFTBACK, 'Лифтбэк'),
        (JEEP, 'Джип'),
        (UNIVERSAL, 'Универсал'),
        (MINIVAN, 'Минивэн'),
        (PIKUP, 'Пикап'),
    )
    
    AUTOMAT = 'AT'
    MECHANIC = 'MC'
    
    GEAR_CHOICES = (
        (AUTOMAT, 'АКПП'),
        (MECHANIC, 'МКПП'),
    )
    
    brand = models.CharField(verbose_name='Марка', max_length=100, blank=False, null=False)
    model = models.CharField(verbose_name='Модель', max_length=100, blank=False, null=False)
    carType = models.CharField(verbose_name='Тип Кузова', max_length=2, choices=CATEGORY_CHOICES,blank=True, null=True)
    regNumber = models.CharField(verbose_name='Рег. номер', max_length=20, blank=True, null=True)
    yearIssu = models.IntegerField(verbose_name='Год выпуска', blank=False, null=False)
    status = models.BooleanField(default=False, verbose_name='Занят/Свободен')
    driver = models.ManyToManyField(Driver, through='DriverMany')
    discription = models.TextField(verbose_name='Описание', blank=True, null=True)
    image = models.ImageField(upload_to='images/cars/%Y-%m-%d/', verbose_name='Загрузить Фото')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания' )
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата изменения', null=True )
    city = models.ForeignKey(CityPark, on_delete=models.SET_NULL, verbose_name='Город', null=True)
    price = models.IntegerField(verbose_name='Цена', blank=True, null=True)
    gearType = models.CharField(verbose_name='Коробка передач', max_length=2, choices=GEAR_CHOICES, blank=False, null=False)
    engineCapacity = models.FloatField(verbose_name='Обьем двигателя', max_length=100, blank=False, null=False)
    class Meta:
        verbose_name_plural = "Автомобили"
        verbose_name = 'Автомобиль'
    
    def __str__(self):
        return f'{self.brand} {self.model} {self.regNumber} - {self.city}'
    
class ParkManager(models.Model):
    firstName = models.CharField(max_length=100, blank=False, null=False, verbose_name='Имя')
    lastName = models.CharField(max_length=100, verbose_name='Фамилия', blank=True, null=True)
    thirdName = models.CharField(max_length=100, verbose_name='Отчесвто', blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, null=False, blank=False, verbose_name='Телефон')
    email = models.EmailField(verbose_name='Почта')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата изменения', null=True )
    city = models.ForeignKey(CityPark, on_delete=models.SET_NULL, verbose_name='Город', null=True)
    position = models.CharField(max_length=200, verbose_name='Должность')
    image = models.ImageField(upload_to='images/managers/%Y-%m-%d/', verbose_name='Загрузить Фото', null=True, blank=True)
    discription = models.TextField(verbose_name='Описание', blank=True, null=True)
    
    
    class Meta:
        verbose_name_plural = "Менеджеры таксопарков"
        verbose_name = 'Менеджер таксопарка'
    
    def __str__(self) -> str:
        return f'{self.firstName} {self.lastName} - {self.city}'
    
class CarPark(models.Model):
    name = models.CharField(verbose_name='название таксопарка', max_length=50, blank=False, null=False)
    parkManager = models.ForeignKey(ParkManager, on_delete=models.SET_NULL, verbose_name='Менеджер', null=True)
    city = models.ForeignKey(CityPark, on_delete=models.CASCADE, verbose_name='Город')
    address = models.TextField(verbose_name='Адрес')
    phone_number = PhoneNumberField(unique=True, verbose_name='Телефон')
    taxiCar = models.ManyToManyField(TaxiCar, through='TaxiCarMany', verbose_name='Автомобили')
    dateCreation = models.DateTimeField(auto_now_add=True)
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата изменения', null=True )
    
    class Meta:
        verbose_name_plural = "Таксопарки автомобилей"
        verbose_name = 'Таксопарк автомобилей'
        
    def __str__(self):
        return f'г. {self.city}, таксопарк - {self.name}'
    
class FeedbackVideo(models.Model):
    city = models.ForeignKey(CityPark, on_delete=models.CASCADE, verbose_name='Город', null=False)
    name = models.CharField(verbose_name='Название видео', max_length=50, blank=False, null=False)
    video = models.FileField(upload_to='video/feedback/%Y-%m-%d/', verbose_name='Видеофайл',blank=True, null=True,)
    youtube = EmbedVideoField(blank=True, null=True, verbose_name='Youtube ссылка')
    dateCreation = models.DateTimeField(auto_now_add=True)
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата изменения', null=True )
    
    
    class Meta:
        verbose_name_plural = "Видеоотзывы"
        verbose_name = 'Видеоотзыв'
        
    def __str__(self):
        return f'г.{self.city} {self.name}' 
    
class VideoAbout(models.Model):
    name = models.CharField(verbose_name='Название видео', max_length=50, blank=False, null=False)
    video = models.FileField(upload_to='video/videoabout/%Y-%m-%d/', verbose_name='Видеофайл', blank=True, null=True,)
    youtube = EmbedVideoField(blank=True, null=True, verbose_name='Youtube ссылка')
    dateCreation = models.DateTimeField(auto_now_add=True)
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата изменения', null=True )
    
    
    class Meta:
        verbose_name_plural = "Видеo о нас"
        verbose_name = 'Видео о нас'
        
    def __str__(self):
        return f'Видео о нас' 
    
class TaxiCarMany(models.Model):
    carParkThrough = models.ForeignKey(CarPark, on_delete=models.CASCADE)
    taxiCarThrough = models.ForeignKey(TaxiCar, on_delete=models.CASCADE, verbose_name="автомобили таксопарка") 
    
    def __str__(self):
        return ' '
    
class DriverMany(models.Model):
    taxiCarThrough = models.ForeignKey(TaxiCar, on_delete=models.CASCADE)
    driverThrough = models.ForeignKey(Driver, on_delete=models.CASCADE, verbose_name="автомобиль арендовали")
    
    def __str__(self):
        return ' '
    
    

etaxi/templates/includes/cars.html
{%load static%}
<section class="catalog" id="catalog">
   <h2 class="catalog-title title">Автомобили нашего таксопарка</h2>
   <h4 class="catalog-age">Все авто не старше 2-х лет</h4>

   
   <div class="catalog-inner cars-desktop" id="catalog-inner "> 
    {%if cars%}
       {%for car in cars%}
       <div class="catalog__item">
           <figure class="catalog-img">
               <img src="{{car.image.url}}" alt="Volkswagen Polo">
           </figure>
           <h3 class="catalog-subtitle subtitle">{{car.brand}} {{car.model}}</h3>
           <ul class="catalog-text text">
               <li>Год выпуска: {{car.yearIssu}} г.</li>
               <li>{{car.get_gearType_display|safe}}</li>
               <li>Объем двигателя {{car.engineCapacity}} л</li>
               <li>Авто на газу — экономия 200 р/ 100 км в сравнении с бензином</li>
           </ul>
           <button class="button catalog__button">Арендовать</button>
       </div>
       {%endfor%}
    {%endif%}
        <div class="catalog__controls">
            <figure class="catalog__control">
                <img class="prev-catalog catalog-controlls" src="{%static 'img/btn-arrow-left.svg'%}" alt="">
            </figure>
            <figure class="catalog__control">
                <img class="next-catalog catalog-controlls" src="{%static 'img/btn-arrow-right.svg'%}" alt="">
            </figure>
        </div>
   </div>

   <div class="catalog-inner cars-mobile itc-slider" id="catalog-inner" data-slider="itc-slider" data-loop="true">
      
       <div class="itc-slider-wrapper">
         <div class="itc-slider-items">
            {%if cars%}
            {%for car in cars%}
            <div class="catalog__item itc-slider-item">
                <figure class="catalog-img">
                    <img src="{{car.image.url}}" alt="Volkswagen Polo">
                </figure>
                <h3 class="catalog-subtitle subtitle">{{car.brand}} {{car.model}}</h3>
                <ul class="catalog-text text">
                    <li>Год выпуска: {{car.yearIssu}} г.</li>
                    <li>{{car.get_gearType_display|safe}}</li>
                    <li>Объем двигателя {{car.engineCapacity}} л</li>
                    <li>Авто на газу — экономия 200 р/ 100 км в сравнении с бензином</li>
                </ul>
                <button class="button catalog__button">Арендовать</button>
            </div>
            {%endfor%}
            {%endif%}
                
         </div>
       </div>

        <div class="catalog__controls">
            <figure class="catalog__control ">
                <img class="prev-catalog catalog-controlls itc-slider-btn itc-slider-btn-prev" src="{%static 'img/btn-arrow-left.svg'%}" alt="">
            </figure>
            <figure class="catalog__control">
                <img class="next-catalog catalog-controlls itc-slider-btn itc-slider-btn-next" src="{%static 'img/btn-arrow-right.svg'%}" alt="">
            </figure>
        </div>
   </div>

</section>

etaxi/templates/includes/contacts.html
{%load static%}

<section class="contacts" id="contacts">
   <div class="contacts__inner">
{% if citygeo.name == 'Барнаул' %}
    {% include 'maps_main/ppageContactsBarnaul.html' %}
{% elif citygeo.name == 'Екатеринбург' %}
    {% include 'maps_main/ppageContactsEkaterinburg.html' %} 
{% elif citygeo.name == 'Иркутск' %}
    {% include 'maps_main/ppageContactsIrkutsk.html' %}
{% elif citygeo.name == 'Кемерово' %}
    {% include 'maps_main/ppageContactsKemerovo.html' %}
{% elif citygeo.name == 'Красноярск' %}
    {% include 'maps_main/ppageContactsKrasnoiarsk.html' %}
{% elif citygeo.name == 'Новокузнецк' %}
    {% include 'maps_main/ppageContactsNovokuznetsk.html' %}
{% elif citygeo.name == 'Новосибирск' %}
    {% include 'maps_main/ppageContactsNovosibirsk.html' %}
{% elif citygeo.name == 'Омск' %}
    {% include 'maps_main/ppageContactsOmsk.html' %}
{% elif citygeo.name == 'Томск' %}
    {% include 'maps_main/ppageContactsTomsk.html' %}
{% elif citygeo.name == 'Тюмень' %}
    {% include 'maps_main/ppageContactsTumen.html' %}
{% elif citygeo.name == 'Улан-Удэ' %}
    {% include 'maps_main/ppageContactsUlanUde.html' %}
{%endif%}

   </div>
</section>

etaxi/templates/includes/footer.html
{%load static%}
<footer class="footer">
   <div class="container">
     <div class="footer-inner">
       <div class="footer-up">
         <div class="footer-logo">
           <a href="{% url 'etaxi:homecity' citygeo.name %}"><img class="footer-logo__img" src="{%static 'img/logo.svg'%}" alt="etaxi logo"></a>
         </div>
         <div class="footer-phone-social">
           <a class="footer-phone" href="tel:+73822984033">+7 (382) 298-40-33</a>
           <div class="footer-social">
             <a href="https://web.telegram.org/a/#970433058" target="_blank">
               <img src="{%static 'img/Telegram.svg'%}" alt="Telegram">
             </a>
             <a href="https://www.youtube.com/channel/UCGadPlvl5Eq5b1NHnGs5m0w" target="_blank">
               <img src="{%static 'img/Youtube.svg'%}" alt="Youtube">
             </a>
             <a href="https://vk.com/etaxidriver" target="_blank">
               <img src="{%static 'img/Vk.svg'%}" alt="Vk">
             </a>
           </div>
         </div>
       </div>
       <div class="footer__down">
         <div class="copyright">&#9400 2023 Все права защищены</div>
         <nav class="nav-footer">
           <ul class="nav-list">
             <li class="nav__item-footer">
               <a class="nav__link-footer" href="{%url 'etaxi:homecity' citygeo.name%}#catalog">Каталог</a>
             </li>
             <li class="nav__item-footer">
               <a class="nav__link-footer" href="{%url 'etaxi:about' citygeo.name%}">О нас</a>
             </li>
             <li class="nav__item-footer">
               <a class="nav__link-footer" href="{%url 'etaxi:homecity' citygeo.name%}#rent">Условия аренды</a>
             </li>
             <li class="nav__item-footer">
               <a class="nav__link-footer" href="{%url 'etaxi:homecity' citygeo.name%}#reviews">Отзывы</a>
             </li>
             <li class="nav__item-footer">
               <a class="nav__link-footer" href="{%url 'etaxi:homecity' citygeo.name%}#contacts">Контакты</a>
             </li>
           </ul>
         </nav>
         <div class="privacy-policy">Политика конфиденциальности</div>
       </div>
     </div>
   </div>
</footer>

etaxi/templates/includes/form_popup.html
{%load static%}

{%if novalid%}
<script defer src="{%static 'js/applicationApp.js'%}"></script>
<form class="application-form" style="display: flex; margin-bottom: 10vh;" action="" method="POST" id="reg-form">
{%else%}
<form class="application-form" action="" method="POST" id="reg-form">
{%endif%}
   {% csrf_token %}
   <figure class="application-close">
       <img src="{%static 'img/close-form.svg'%}">
   </figure>
   <h2 class="application-subtitle">Оставите заявку</h2>
   <h3 class="application-text">Первый день аренды авто бесплатно!</h3>
   {{ form.name }}
   <div class="form-error">{{ form.name.errors }}</div>
   {{ form.phone_number }}
   <div class="form-error">{{ form.phone_number.errors }}</div>

   <div style="display: none;">{{ form.city }}
        <div class="form-error">{{ form.city.errors }}</div>
   </div>
   <button class="button application-button" type="submit">Оставить заявку</button>
   <div class="application-checkbox">
   {{form.confirmation}}
   <label class="application-checkbox" for="confirmation">Подтверждаю согласие на обработку персональных данных и соглашаюсь с политикой конфиденциальности</label>
   </div>
</form>

<div class="popUp">
   <figure class="application-close popUp-close">
       <img src="{%static 'img/close-form.svg'%}">
   </figure>
   <h4 class="popUp-title">Выберите город</h4>
   <div class="popUp-search-city">
       <input class="popUp-city" placeholder="Ваш город">
       <figure class="popUp-img-city">
           <img src="{%static 'img/search.svg'%}" alt="search">
       </figure>
       <div class="popUp-list">
           {%for city in cities%}
           <a class="popUp__item" href="{% url 'etaxi:homecity' city.name %}">{{city}}</a>
           {%endfor%}
       </div>
   </div>
</div>

etaxi/templates/includes/header.html
{%load static%}
<header id="header-section">
   <div class="container">

    <!-- НОВОЕ БУРГЕР МЕНЮ с формой НАЧАЛО -->
    <!-- <form class="application-formBurger" action="" method="post">
        <figure class="application-closeBurger">
            <img src="{%static 'img/menu-burgerClose.svg'%}">
        </figure>
        <h2 class="application-subtitleBurger">Оставьте заявку</h2>
        <h3 class="application-textBurger">Первый день аренды авто бесплатно!</h3>
        <input class="application-inputBurger" type="text" name="name" placeholder="Ваше имя" required></input>
        <input class="application-inputBurger" type="tel" name="tel" placeholder="+7 (999) 999-99-99" required></input>
        <div class="dropDown-mainBurger">
            <div class="dropDown-main-selectCityBurger">
              <input class="dropDown-main-cityBurger" placeholder="Выберите город"></input>
              <figure class="dropDown-main-img-downBurger">
                <img src="{%static 'img/expand_more.svg'%}" alt="expand more">
              </figure>
              <figure class="dropDown-main-img-upBurger">
                <img src="{%static 'img/expand_more_up.svg'%}" alt="expand more">
              </figure>
            </div>
            <div class="dropDown-main-listBurger">
                    <div class="dropDown-main__itemBurger">Иркутск</div>
                    <div class="dropDown-main__itemBurger">Барнаул</div>
                    <div class="dropDown-main__itemBurger">Екатеринбург</div>
                    <div class="dropDown-main__itemBurger">Кемерово</div>
                    <div class="dropDown-main__itemBurger">Красноярск</div>
                    <div class="dropDown-main__itemBurger">Новосибирск</div>
                    <div class="dropDown-main__itemBurger">Новокузнецк</div>
                    <div class="dropDown-main__itemBurger">Омск</div>
                    <div class="dropDown-main__itemBurger">Томск</div>
                    <div class="dropDown-main__itemBurger">Тюмень</div>
                    <div class="dropDown-main__itemBurger">Улан-Удэ</div>
            </div>
        </div>
        <button class="application-button-burger">Оставить заявку</button>
        <div class="application-checkboxBurger">
            <input class="custom-checkboxBurger" type="checkbox" id="confirmationBurger" name="confirmationBurger"/>
            <label class="application-checkboxBurger" for="confirmationBurger">Подтверждаю согласие на обработку персональных данных и соглашаюсь с политикой конфиденциальности</label>
        </div>
    </form> -->

    <!-- НОВОЕ БУРГЕР МЕНЮ с формой Конец -->

       <div class="actual-city">
           <div class="actual-city-top">
               <figure class="city-img-actual">
                   <img src="{%static 'img/location_city.svg'%}" alt="location icon">
               </figure>
               <h4 class="city-text">Ваш город <span class="your-city">{{citygeo}}</span>?</h4>
           </div>
           <div class="actual-city-bottom">
               <button class="button actual-city__button actual-city__button--yellow">Всё верно</button>
               <button class="actual-city__button actual-city__button--white">Выбрать город</button>
           </div>
       </div>
       <div class="header">
           <div class="header-logo">
               <a href="{% url 'etaxi:homecity' citygeo.name%}"><img class="header-logo__img" src="{%static 'img/logo.svg'%}" alt="etaxi logo"></a>
           </div>
           <div class="header-description">
               <div class="header-top">
                   <figure class="header-geo">
                       <img src="{%static 'img/location-header.svg'%}" alt="location">
                   </figure>
                   <span class="header-city">{{citygeo}}</span>
                   <figure class="header-expandMore">
                       <img src="{%static 'img/expand_more.svg'%}" alt="expand_more">
                   </figure>
                   <figure class="header-mode">
                       <img src="{%static 'img/clock-header.svg'%}" alt="clock">
                   </figure>
                   <span class="operating-mode">пн-пт 9:00–18:00, сб 10:00–14:00</span>
                   <figure class="header-call">
                       <img src="{%static 'img/call-header.svg'%}" alt="call">
                   </figure>
                   <a class="header-number" href="tel:+73822984033">+7 (382) 298-40-33</a>
               </div>       
               <div class="header-bottom">
                   <nav class="header-nav">
                       <ul class="header-nav-list">
                           <!-- <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:home'}">Главная</a></li>     -->
                           <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#catalog">Каталог</a></li>
                           <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#rent">Условия аренды</a></li>
                           <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#reviews">Отзывы</a></li>
                           <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:contacts' citygeo.name%}">Контакты</a></li>
                           <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:about' citygeo.name%}">О нас</a></li>
                       </ul>
                   </nav>
                   <button class="button header-nav__button">Оставить заявку</button>
               </div>   
           </div>

           <!-- ЕЩЕ БУРГЕР МЕНЮ НАЧАЛО -->
           <div class="menu-burger">
            <figure class="burger-open">
                <img src="{%static 'img/menu-burgerOpen.svg'%}" alt="menu">
            </figure>
            <figure class="burger-close">
                <img src="{%static 'img/menu-burgerClose.svg'%}" alt="menu">
            </figure>
            
            <div class="menu-burger__list">
                <ul class="menu-burger__items">
                    <div class="header-logo header-logo-burger">
                        <a href="{% url 'etaxi:homecity' citygeo.name%}"><img class="header-logo__img" src="{%static 'img/logo.svg'%}" alt="etaxi logo"></a>
                    </div>
                    <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#catalog">Каталог</a></li>
                    <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#rent">Условия аренды</a></li>
                    <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:homecity' citygeo.name%}#reviews">Отзывы</a></li>
                    <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:contacts' citygeo.name%}">Контакты</a></li>
                    <li class="header-nav__item"><a class="header-nav__link" href="{%url 'etaxi:about' citygeo.name%}">О нас</a></li>
                </ul>
                <div class="menu-burger__number">
                    <figure class="call-burger">
                        <img src="{%static 'img/call-header.svg'%}" alt="call">
                    </figure>
                    <a class="number-burger" href="tel:+73822984033">+7 (382) 298-40-33</a>
                </div>
                <button class="button burger-nav__button">Оставить заявку</button>

            </div>
        </div>
            <!-- ЕЩЕ БУРГЕР МЕНЮ Конец -->

       </div>
    </div>   
</header>

etaxi/templates/includes/offers.html
{%load static%}

<section class="offers">
   <figure class="offer-img">
       <img src="{%static 'img/banner_offer.png'%}" alt="banner offer">
   </figure>
   <div class="offer-item">
       <h2 class="offer-title title">Первый день аренды</h2>
       <h2 class="offer-title offer-title-free title">Бесплатно*</h2>

       <form class="offer-form" action="" method="POST">
        {% csrf_token %}
        {{ formoffer.name }}
        <div class="form-error">{{ formoffer.name.errors }}</div>
        {{ formoffer.phone_number }}
        <div class="form-error">{{ formoffer.phone_number.errors }}</div>
        <button class="button offer__button" type="submit">Арендовать машину</button>
        <div class="offer-form__checkbox">
        {{formoffer.confirmation}}
        <label for="verification">Подтверждаю согласие на обработку персональных данных и соглашаюсь с политикой конфиденциальности</label>
        </div>
        </form>
       <h3 class="offer-text">* В отдельных случаях компания оставляет за собой право не применять настоящее условие. Подробности уточняйте у сотрудников компании.</h3>
   </div>
</section>

etaxi/templates/includes/rent.html
{%load static%}
<section class="rent" id="rent">
    <h2 class="rent-title title">Условия аренды</h2>
    <ul class="rent-list">
        <li class="rent__item">
            <span>Водительские права категории "B"</span>
        </li>
        <li class="rent__item">
            <span>Стаж вождения не менее 3-х лет</span>
        </li>
    </ul>
    <h2 class="stage-rent-title title">Этапы аренды автомобиля</h2>
    <div class="stage-rent-inner">
        <div class="stage-rent__item">
            <div class="stage-rent-number">1</div>
            <div class="stage-description">
                <div class="stage-rent-subtitle subtitle">Заявка на сайте</div>
                <p class="stage-rent-text text">Выберите желаемую модель автомобиля, заполните заявку на сайте и отправьте её</p>
            </div>
        </div>
        <div class="stage-rent__item">
            <div class="stage-rent-number">2</div>
            <div class="stage-description">
                <div class="stage-rent-subtitle subtitle">Собеседование</div>
                <p class="stage-rent-text text">Вам перезвонит менеджер, ответит на все вопросы и пригласит на собеседование</p>
            </div>
        </div>
        <div class="stage-rent__item">
            <div class="stage-rent-number">3</div>
            <div class="stage-description">
                <div class="stage-rent-subtitle subtitle">Проверка</div>
                <p class="stage-rent-text text">Проверка службой безопасности по анкете, заполненной на собеседовании</p>
            </div>
        </div>
        <div class="stage-rent__item">
            <div class="stage-rent-number">4</div>
            <div class="stage-description">
                <div class="stage-rent-subtitle subtitle">Обучение</div>
                <p class="stage-rent-text text">Инструктаж и подписание договора на аренду машины под такси</p>
            </div>
        </div>
        <div class="stage-rent__item">
            <div class="stage-rent-number">5</div>
            <div class="stage-description">
                <div class="stage-rent-subtitle subtitle">Автомобиль</div>
                <p class="stage-rent-text text">Выдача автомобиля и начало работы в Яндекс Такси</p>
            </div>
        </div>
    </div>
    <div class="stage-rent-connect">Уже через 1-2 часа после звонка вы получите автомобиль!</div>
</section>